import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "DevTasks",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <header className="text-3xl font-bold leading-[4rem]">
          <Link href="/">DevTasks</Link>
        </header>
        <main className="">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
         Lucas Gotz Baliner © {new Date().getFullYear()} 
        </footer>
      </body>
    </html>
  );
}
